In [1]:
import numpy as np
from verma_net_radiation import brutsaert_atmospheric_emissivity

In [2]:
Ea_Pa = np.load("Ea_Pa.npy", allow_pickle=True)
Ea_Pa

array([2766.5550868059654, 2766.5550868059654, 2766.5550868059654, ...,
       1658.586944508865, 1658.586944508865, 1658.586944508865],
      shape=(106300,), dtype=object)

In [3]:
type(Ea_Pa)

numpy.ndarray

In [4]:
np.nanmin(Ea_Pa)

148.1866571434283

In [5]:
np.isreal(Ea_Pa).all()

np.True_

In [6]:
Ta_K = np.load("Ta_K.npy", allow_pickle=True)
Ta_K

array([305.80892, 305.80892, 305.80892, ..., 303.466103, 303.466103,
       303.466103], shape=(106300,), dtype=object)

In [7]:
type(Ta_K)

numpy.ndarray

In [8]:
np.isreal(Ta_K).all()

np.True_

In [9]:
np.nanmin(Ta_K)

258.54495199999997

In [10]:
result = brutsaert_atmospheric_emissivity(
    Ea_Pa=Ea_Pa,
    Ta_K=Ta_K
)

result

array([0.87351031, 0.87351031, 0.87351031, ..., 0.81841724, 0.81841724,
       0.81841724], shape=(106300,))